#!/bin/sh

bundle exec rake assets:precompile --trace

export SECRET_KEY_BASE=$(rake secret)

bundle exec rake db:setup || true
bundle exec rake db:migrate

bundle exec sidekiq -d -C config/sidekiq.yml
bundle exec rails server -b 0.0.0.0
